---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    ingress-ready: true
  extraPortMappings:
  - containerPort: 8080
    hostPort: 80
    protocol: TCP
  - containerPort: 8443
    hostPort: 443
    protocol: TCP
- role: worker
- role: worker

