---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  namespace: default
spec:
  containers:
    serviceAccountName: prometheus
  - name: prometheus
    image: prom/prometheus:v2.32.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: prometheus-vol
      mountPath: /prometheus
    ports:
    - containerPort: 9090
      name: prometheus
  volumes:
  - name: prometheus-vol
    persistentVolumeClaim:
      claimName: prometheus-pvc 

