---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: awx-operator
    repoURL: https://ansible.github.io/awx-operator/
    targetRevision: 2.15.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: clusterip
