---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: awx-operator
    repoURL: https://ansible.github.io/awx-operator/
    targetRevision: 2.15.0
  helm:
    values:
      # the 'password' key in this secret is what gets looked up
      admin_password_secret: awx-admin-password
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  service_type: clusterip
