apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jetstack.yaml
- minecraft.yaml
- nfs-subdir-external-provisioner.yaml
- prometheus-stack.yaml
- authentik.yaml
- traefik.yaml
- longhorn.yaml
