apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:YHd/vorqzrAcjyJM04Y=,iv:I8YteMfkMb3ZY9LOlZjGVdtkzKYRYm8RZ0dZQ97d4eI=,tag:211OAvT3EFzvK8NAHcIIdw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:M7U7Miy2vqxphSZ43yepDaLUJ02uSoriJyTXN4ABYJu+My/HOAmOozmNwD5bqjm4tUs=,iv:1YRq8CvCp5y62P7VJD8qrT/QDw+NLR3zMa2csmlR2O4=,tag:8dwDA/13UmXx1HCLy6oRzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fg5xd2nehtrqx0mzhq606yn02fnc06fpevyrpwzpraxh6c23nunqp49lx6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ2Z6OXNNK1gvVjVTSThh
            MnVxTUs3OXhkWGY3alA4Tjc0VUVZcUM1cTJJCjk5cjFvY1dXdTEwQXYrS0VNMnd1
            Y3QxNXZsdzRQUnp4T3FSc09rdUltckkKLS0tIDRxNWN3TGFud3NXdDU2cTFyM2pK
            cUtOeEpsaExObGJicHl4SVhESVRsRVUKqA8sIEkS/e0QpjSgloL1RvfzBCoq7q8w
            7z0UbocQ4Ne5zMFaZDVrkD6Pqv9YnStrhavmLF3xdhLkREmJgnDE5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T20:43:59Z"
    mac: ENC[AES256_GCM,data:Biqb5RJowycNK6+FylXTXfkw6PwohtXU4QEfEV2Nur+yhmR/d2W33eNpu5r/TrSDo1blIbEyCMcKHxPAIBVSDunCtS3yMpVBxW6HlAK0ElUU420V8o/SEMnrqEVk7XKaA4zuL8J6PnLDx6jqvgVhNiYQdyprzf1t/My5xOhGRd0=,iv:xDcm6VehoCuAIB2g/mJrsSIvGPheyphDGaMo7H92VL0=,tag:p1mDluaBK44ANGaLVolWNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
