apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-release.yaml
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: authentik-secrets
        namespace: authentik
