apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: authentik
stringData:
    AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:jdEiEJxuivhCFDhYGxU=,iv:+L1DAY+XxJR3koIW6gRQuOyNYNYi1u0MsA6DN5HBVBc=,tag:Q1HD9YuxX1lxGQgI3PT7Kg==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Jf/kmnhvZe53pANpQ5i2sJS1rJa1FpFFYgfd8vnlfqARs89a0oOwSBilhPljJ9o3whs=,iv:jQjmEYQ2vWlj0ohd32473l/ulukjiB0Sd8kyr0T7qqs=,tag:FrX7+SZRXkonKA2eXHOuQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-22T19:36:53Z"
    mac: ENC[AES256_GCM,data:rH7IBlErYDFjDej9bUy/Dv3JOOxeELdC9pocFXbxtvoR853eoOlRblpCKGI0D8+hxsYf2tQraw+6Hv/LTxdtj2jjYK0ygwqUYF0WuctpeLStuS8oA3OWcgPzbw+4/Tzfy910DLT2GAuFpljuamBYW+otRw02Ax7QT0WwpNgXYwY=,iv:ZN1Lbhc5v4GBwbq2ZXTPwNioFr2go+9gtWeVHc2NbO0=,tag:ZEkOQ/tdhb0ESz8MpYqX9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
