# apply this manifest to have everything else appear 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-core/traefik
    repoURL: https://github.com/danielpodwysocki/kube.git
    targetRevision: HEAD


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-apps/echo-server
    repoURL: https://github.com/danielpodwysocki/kube.git
    targetRevision: HEAD

