---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: {{ .Values.danielpodwysocki.longhorn_chart_version }}
    chart: longhorn
    helm:
      values: | {{ .Values.longhorn | toYaml | nindent 8 }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: {{ .Values.danielpodwysocki.velero_chart_version }}
    chart: velero
    helm:
      values: | {{ .Values.velero | toYaml | nindent 8 }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: {{ .Values.danielpodwysocki.metallb_chart_version }}
    chart: metallb
    helm:
      values: | {{ .Values.metallb | toYaml | nindent 8 }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: {{ .Values.danielpodwysocki.sealed_secrets_chart_version }}
  syncPolicy:
    automated: {}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: {{ .Values.danielpodwysocki.cert_manager_chart_version }}
    chart: cert-manager
    helm:
      values: | {{ .Values.cert_manager | toYaml | nindent 8 }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-configuration
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/common/metallb-configuration
    repoURL: https://github.com/danielpodwysocki/kube.git
    targetRevision: {{ .Values.danielpodwysocki.targetRevision }}
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/common/traefik
    repoURL: https://github.com/danielpodwysocki/kube.git
    targetRevision: {{ .Values.danielpodwysocki.targetRevision }}
  syncPolicy:
    automated: {}

