---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: {{ .Values.danielpodwysocki.metallb_chart_version }}
    chart: metallb
    helm:
      values: | {{ .Values.metallb | toYaml | nindent 8 }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: danielpodwysocki-common-sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: {{ .Values.danielpodwysocki.sealed_secrets_chart_version }}
  syncPolicy:
    automated: {}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: danielpodwysocki-common-metallb-configuration
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/common/metallb-configuration
    repoURL: https://github.com/danielpodwysocki/kube.git
    targetRevision: {{ .Values.danielpodwysocki.targetRevision }}
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: danielpodwysocki-common-traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/common/traefik
    repoURL: https://github.com/danielpodwysocki/kube.git
    targetRevision: {{ .Values.danielpodwysocki.targetRevision }}
  syncPolicy:
    automated: {}


