---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: danielpodwysocki-common-metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/common/metallb
    repoURL: https://github.com/danielpodwysocki/kube.git
    targetRevision: {{ .Values.danielpodwysocki.targetRevision }}
  syncPolicy:
    createNamespace: true
    automated: {}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: danielpodwysocki-common-metallb-configuration
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/common/metallb-configuration
    repoURL: https://github.com/danielpodwysocki/kube.git
    targetRevision: {{ .Values.danielpodwysocki.targetRevision }}
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: danielpodwysocki-common-traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/common/traefik
    repoURL: https://github.com/danielpodwysocki/kube.git
    targetRevision: {{ .Values.danielpodwysocki.targetRevision }}
  syncPolicy:
    automated: {}

