---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: {{ .Values.danielpodwysocki.traefik_chart_version }}
    helm:
      values: | {{ .Values.traefik | toYaml | nindent 8 }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

