---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: {{ .Values.danielpodwysocki.velero_chart_version }}
    chart: velero
    helm:
      values: | {{ .Values.velero | toYaml | nindent 8 }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
